// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3WzG49z5cRAPASaBB9D-4gS1exiiIweo',
    appId: '1:869684477540:android:497d032616756595da6971',
    messagingSenderId: '869684477540',
    projectId: 'smartrent-7af23',
    storageBucket: 'smartrent-7af23.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2Q_zdAofpwgiQAfuaxPa-___R5iQ5EQI',
    appId: '1:869684477540:ios:62f8d5815871a4e9da6971',
    messagingSenderId: '869684477540',
    projectId: 'smartrent-7af23',
    storageBucket: 'smartrent-7af23.firebasestorage.app',
    iosBundleId: 'com.example.smartrentMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCu-9z4on5Lyha4-59re_KkUgPEytlywb8',
    appId: '1:869684477540:web:436d9cf1988ebaa8da6971',
    messagingSenderId: '869684477540',
    projectId: 'smartrent-7af23',
    authDomain: 'smartrent-7af23.firebaseapp.com',
    storageBucket: 'smartrent-7af23.firebasestorage.app',
    measurementId: 'G-0TCE98SHCC',
  );
}
